apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
          - name: OLLAMA_BASE_URLS
            value: "http://ollama-service:7869"
        volumeMounts:
        - name: webui-data
          mountPath: /app/backend/data
      volumes:
      - name: webui-data
        hostPath:
        persistentVolumeClaim:
          claimName: webui-pvc
