apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /c/SBX/cloud/Projekt/ollama/grafana
  claimRef:
     namespace: default
     name: grafana-pvc

