apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/SBX/cloud/Projekt/ollama/ollama
  claimRef:
     namespace: default
     name: ollama-pvc
