apiVersion: v1
kind: PersistentVolume
metadata:
  name: webui-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/SBX/cloud/Projekt/ollama/ollama-webui
  claimRef:
     namespace: default
     name: webui-pvc
